import { AlertCircle, Boxes, DollarSign, Package, ShoppingBag, Users } from "lucide-react";
import type { AdminDashboardOverview as Overview } from "@/db";
import { formatTk } from "@/components/zupona/data";
import { AdminActivityFeed } from "./AdminActivityFeed";
import { AdminKpiCard } from "./AdminKpiCard";
import { AdminProductHealth } from "./AdminProductHealth";
import { AdminRecentOrders } from "./AdminRecentOrders";
import { AdminSalesOverview } from "./AdminSalesOverview";

const display = (value: number | null, format = false) => value === null ? "Unavailable" : format ? formatTk(value) : value.toLocaleString();

export function AdminDashboardOverview({ overview, loading, error, onAddProduct, onSectionChange }: { overview: Overview | null; loading: boolean; error: string; onAddProduct: () => void; onSectionChange: (section: "catalog" | "orders" | "settings" | "tools") => void }) {
  if (loading) return <div className="space-y-5"><div className="h-24 animate-pulse rounded-2xl bg-slate-200" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-32 animate-pulse rounded-2xl bg-slate-200" />)}</div><div className="h-64 animate-pulse rounded-2xl bg-slate-200" /></div>;
  if (error || !overview) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-700"><div className="flex items-center gap-2 font-bold"><AlertCircle className="h-4 w-4" />Dashboard unavailable</div><p className="mt-2 text-xs">{error || "No dashboard data is available."}</p></div>;
  return <div className="space-y-5"><div className="flex flex-col gap-4 rounded-2xl bg-gradient-to-br from-[#171b3d] via-[#25265a] to-[#3f327c] p-6 text-white shadow-xl shadow-violet-950/10 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold text-violet-200">Owner workspace</p><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Good morning, Sajid!</h1><p className="mt-2 max-w-xl text-xs text-violet-100/80">A clear view of your store, grounded in the data currently persisted in D1.</p></div><p className="text-xs font-semibold text-violet-200">{new Date().toLocaleString()}</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminKpiCard label="Total revenue" value={display(overview.metrics.revenue, true)} icon={DollarSign} tone="violet" /><AdminKpiCard label="Total orders" value={display(overview.metrics.orders)} icon={ShoppingBag} tone="green" /><AdminKpiCard label="Total products" value={display(overview.metrics.products)} icon={Package} tone="blue" /><AdminKpiCard label="Total customers" value={display(overview.metrics.customers)} icon={Users} tone="orange" /></div><div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><AdminSalesOverview sales={overview.sales} /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-violet-600">Shortcuts</p><h2 className="mt-1 text-base font-black text-slate-900">Quick actions</h2><div className="mt-4 grid gap-2">{[["Add product", onAddProduct], ["Manage orders", () => onSectionChange("orders")], ["Site settings", () => onSectionChange("settings")], ["Backup & import", () => onSectionChange("tools")]].map(([label, action]) => <button key={String(label)} type="button" onClick={action as () => void} className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-3 text-left text-xs font-bold text-slate-700 transition-colors hover:border-violet-300 hover:bg-violet-50"><Boxes className="h-4 w-4 text-violet-600" />{String(label)}</button>)}</div></section></div><div className="grid gap-5 xl:grid-cols-2"><AdminRecentOrders orders={overview.recentOrders} /><AdminProductHealth health={overview.productHealth} /></div><AdminActivityFeed activity={overview.activity} /><div className="rounded-2xl border border-slate-200 bg-white p-4 text-xs text-slate-500 shadow-sm">Store health: D1 is <strong className="text-slate-800">{overview.health.database}</strong> · active categories: <strong className="text-slate-800">{overview.health.categories === null ? "Unavailable" : overview.health.categories}</strong></div></div>;
}